version: "3.8"

services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql # EN WINDOWS quitar punto
# volumes: # EN WINDOWS, descomentar bloque
  # postgresql-volume:
    # external: true
