services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=sn-db
      - POSTGRES_USER=db-admin
      - POSTGRES_PASSWORD=7a8s9.g5h6
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql # EN WINDOWS quitar punto
# volumes: # EN WINDOWS, descomentar bloque
  # postgresql-volume:
    # external: true
